### PR TITLE
Proposed

### PR DESCRIPTION
**Pull request by braathwaate**
admin/void_transaction.php: do not unset date to allow subsequent voids on that date
gl/bank_account_reconcile.php: display memo, new "reconcile all" transactions on page feature
gl/gl_journal.php: allow user to retain reconciled status of transaction during modify
gl/includes/db/gl_db_bank_accounts.inc: display memo on bank reconciliation (which often contains check number)
gl/includes/db/gl_db_bank_trans.inc: support for last_bank_trans recall
gl/includes/db/gl_db_trans.inc: support to search gl transactions by memo, fix mantis bug 4161, support for display of transactions with no dimension
gl/includes/ui/gl_bank_ui.inc: recall dimension during supplier payments (prior behavior was no dimension)
gl/includes/ui/gl_journal_ui.inc: allow user to retain reconciled status of transaction
gl/inquiry/gl_account_inquiry.php: support for display of transactions with no dimension, allow search by memo, allow editing of journal entries from G/L inquiry
purchasing/includes/db/suppliers_db.inc: support for dimension recall during supplier payments
reporting/rep105.php: do not generate empty report
reporting/rep106.php: do not generate empty report
reporting/rep108.php: do not generate empty report
reporting/rep114.php: sort by sales type, do not generate empty report
sales/includes/db/sales_invoice_db.inc: support for recall of last sales order item
sales/includes/ui/sales_order_ui.inc: recall last sales order item for new item line (prior behavior was first inventory item, not very useful)

### CODE REVIEW

**Comment by apmuthu** [comment]
Upstream has been notified as it pertains to the `core`. Those changes not accepted may enter the `FA24Mods`.

**Comment by apmuthu** [comment]
@itronics states:

> Bank deposit/payment entry is local operation, which have to be reconciled with bank statement, which you never have when you order bank operation. So I'm not sure what is the expected workflow in which the change is helpful?

**Comment by braathwaate** [comment]
The issue addressed is the modification of already reconciled transactions.   For example, when an accountant reviews entries by data entry staff at the end of an accounting period, often changes are needed, such as to change G/L expense or cogs accounts.   Currently, any modification of any transaction unreconciles it, including something so minor as the memo.   This is usually not what is desired, as then previously reconciled statements must be reanalyzed and reconciled again.

The only workflow in which this change would not be needed is if data entry was perfect during the year and no modification was required or if the user does not reconcile statements.

**Comment by braathwaate** [comment]
Check how this works in any commercial accounting program and compare.   For example, in Quickbooks, it retains the reconciled status except if the amount is changed, in which case, a popup prompts the user about clearing the reconciled status.

**Comment by apmuthu** [comment]
Individual commits assimilated into core.

**Pull request closed without merging**
